-- Insert Experiences
-- This file seeds the experiences table with various travel experiences

INSERT INTO experiences (id, uuid, title, slug, description, short_description, host_id, category_id, experience_type_id, city_id, package_price, currency, duration_hours, max_participants, min_participants, difficulty_level, images, included_items, excluded_items, meeting_point, latitude, longitude, is_active, is_featured, rating_average, rating_count, booking_count, host_specific_data, deliverables, equipment_used, ending_point, walking_distance_km, fitness_level, created_at, updated_at) VALUES

-- Budi Santoso's Experience (Local Tour Guide - Jakarta)
(1, gen_random_uuid(), 'Jakarta Heritage Walking Tour', 'jakarta-heritage-walking-tour', 
 'Discover Jakarta''s rich colonial heritage through Old Town Batavia. Walk through history visiting museums, cafes in colonial buildings, and learn about Dutch influence on Indonesian culture.',
 'Explore Jakarta''s Dutch colonial heritage in historic Old Town Batavia with expert local guide.',
 6, 1, 1, 1, 525000.00, 'IDR', 4, 12, 2, 'easy', 
 '["old-town-jakarta.jpg", "jakarta-heritage.jpg"]'::jsonb,
 '["Professional guide", "Museum entrance fees", "Traditional snack"]'::jsonb,
 '["Personal expenses", "Lunch", "Transportation"]'::jsonb,
 'Jakarta Old Town (Fatahillah Square)', -6.1352, 106.8133, true, true, 4.7, 45, 89, 
 '{"guide_certification": "Jakarta Tourism Board Certified"}'::jsonb,
 '["Historical insights", "Cultural knowledge"]'::jsonb,
 '["Professional camera", "Historical references"]'::jsonb,
 'Jakarta Old Town (Fatahillah Square)', 2.5, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Sari Dewi's Experience (Local Tour Guide - Bali)
(2, gen_random_uuid(), 'Sacred Temples & Rice Terraces Tour', 'sacred-temples-rice-terraces-tour',
 'Discover the spiritual heart of Bali through ancient temples and stunning rice terraces. Experience traditional ceremonies, learn about Hindu-Balinese culture.',
 'Experience spiritual Bali with ancient temples, rice terraces and traditional Hindu ceremonies.',
 7, 1, 3, 2, 1125000.00, 'IDR', 8, 8, 2, 'moderate',
 '["bali-sunrise-yoga.jpg", "bali-photo-walk.jpg"]'::jsonb,
 '["Professional guide", "Temple entrance fees", "Traditional lunch"]'::jsonb,
 '["Personal expenses", "Additional food", "Gratuities"]'::jsonb,
 'Ubud Traditional Market', -8.5069, 115.2625, true, true, 4.9, 156, 320, 
 '{"guide_certification": "Bali Tourism Board Certified"}'::jsonb,
 '["Cultural insights", "Spiritual experience"]'::jsonb,
 '["Cultural knowledge", "Safety equipment"]'::jsonb,
 'Ubud Traditional Market', 5.2, 'moderate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Rina Photography's Experience (Photographer - Jakarta)
(3, gen_random_uuid(), 'Jakarta Portrait Photography Session', 'jakarta-portrait-photography-session',
 'Professional portrait photography session in Jakarta''s most photogenic locations. Capture your memories with stunning backdrops of the city''s iconic landmarks.',
 'Professional portrait photography session in Jakarta''s most beautiful and iconic locations.',
 10, 2, 6, 1, 1200000.00, 'IDR', 2, 4, 1, 'easy',
 '["jakarta-portrait-1.jpg", "jakarta-portrait-2.jpg"]'::jsonb,
 '["Professional photographer", "2-hour photo session", "20+ edited photos"]'::jsonb,
 '["Transportation to location", "Additional photos", "Printing services"]'::jsonb,
 'Hotel Indonesia Roundabout', -6.1944, 106.8229, true, true, 4.8, 73, 156, 
 '{"photographer_experience": "5+ years"}'::jsonb,
 '["High-quality edited photos", "Location recommendations"]'::jsonb,
 '["Professional camera equipment", "Lenses", "Lighting gear"]'::jsonb,
 'Hotel Indonesia Roundabout', 0.5, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Wayan Combo Tours's Experience (Combo - Bali)
(4, gen_random_uuid(), 'Bali Complete Experience Package', 'bali-complete-experience-package',
 'Ultimate Bali experience combining guided tour, professional photography, and custom trip planning. Visit temples, rice terraces, beaches.',
 'Complete Bali package: guided tour, professional photos, and personalized trip planning service.',
 12, 3, 10, 2, 2250000.00, 'IDR', 10, 6, 2, 'moderate',
 '["bali-combo-tour.jpg", "bali-complete-package.jpg"]'::jsonb,
 '["Professional guide", "Professional photographer", "All entrance fees", "Traditional lunch"]'::jsonb,
 '["Personal expenses", "Additional activities", "Accommodation"]'::jsonb,
 'Sanur Beach', -8.6981, 115.2618, true, true, 4.9, 124, 187, 
 '{"services": ["Guiding", "Photography", "Trip Planning"]}'::jsonb,
 '["Complete Bali experience", "Professional photos", "Cultural knowledge"]'::jsonb,
 '["Professional guide equipment", "Photography gear", "Planning materials"]'::jsonb,
 'Sanur Beach', 15.8, 'moderate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Indonesia Travel Pro's Experience (Trip Planner - Jakarta)  
(5, gen_random_uuid(), 'Custom Indonesia Trip Planning Service', 'custom-indonesia-trip-planning-service',
 'Professional trip planning service for your Indonesian adventure. Get personalized itinerary, accommodation recommendations, activity bookings, and local insights.',
 'Professional Indonesian trip planning with personalized itinerary and local expert recommendations.',
 14, 4, 13, 1, 1800000.00, 'IDR', 4, 8, 1, 'easy',
 '["indonesia-planning.jpg", "trip-planning.jpg"]'::jsonb,
 '["Professional consultation", "Detailed itinerary", "Accommodation recommendations", "24/7 support"]'::jsonb,
 '["Actual bookings", "Transportation costs", "Accommodation costs", "Activity fees"]'::jsonb,
 'Virtual Meeting (Online Consultation)', 0.0, 0.0, true, false, 4.8, 95, 142, 
 '{"planning_experience": "10+ years", "coverage": ["All Indonesia"]}'::jsonb,
 '["Detailed itinerary", "Local recommendations", "Booking assistance"]'::jsonb,
 '["Planning software", "Local network", "Travel resources"]'::jsonb,
 'Online Consultation', 0.0, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- NEW EXPERIENCES WITH RUPIAH PRICING

-- Ketut Bali Guide's Experience (Local Tour Guide - Bali)
(6, gen_random_uuid(), 'Mount Batur Sunrise Trekking', 'mount-batur-sunrise-trekking',
 'Experience the magic of Bali sunrise from Mount Batur summit. Early morning trek through volcanic landscape with breakfast cooked by volcanic steam.',
 'Epic sunrise trek up Mount Batur volcano with natural hot spring breakfast experience.',
 25, 1, 4, 2, 450000.00, 'IDR', 6, 15, 2, 'moderate',
 '["mount-batur-sunrise.jpg", "volcanic-breakfast.jpg", "bali-trekking.jpg"]'::jsonb,
 '["Professional guide", "Trekking equipment", "Volcanic steam breakfast", "Hot spring access", "Transportation"]'::jsonb,
 '["Personal expenses", "Tips", "Additional food"]'::jsonb,
 'Hotel pickup Ubud area (3:00 AM)', -8.2421, 115.3753, true, true, 4.9, 156, 203, 
 '{"guide_certification": "Mountain Guide License", "experience_years": 8}'::jsonb,
 '["Sunrise viewing", "Volcanic steam breakfast", "Hot spring relaxation"]'::jsonb,
 '["Trekking poles", "Headlamp", "First aid kit"]'::jsonb,
 'Hotel drop-off Ubud area', 4.5, 'moderate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Joko Jakarta Food's Experience (Local Tour Guide - Jakarta)
(7, gen_random_uuid(), 'Jakarta Street Food Adventure', 'jakarta-street-food-adventure', 
 'Discover authentic Jakarta street food scene from traditional markets to modern food courts. Taste iconic dishes like kerak telor, soto betawi, and es doger.',
 'Ultimate Jakarta street food tour through traditional markets and local eateries.',
 26, 1, 2, 1, 275000.00, 'IDR', 4, 8, 2, 'easy',
 '["jakarta-street-food.jpg", "kerak-telor.jpg", "soto-betawi.jpg"]'::jsonb,
 '["Professional food guide", "All food tastings", "Traditional drinks", "Market entrance"]'::jsonb,
 '["Transportation", "Additional purchases", "Tips"]'::jsonb,
 'Fatahillah Square, Jakarta Old Town', -6.1352, 106.8133, true, false, 4.6, 89, 127, 
 '{"specialization": "Jakarta Culinary Heritage", "food_safety_cert": true}'::jsonb,
 '["Authentic food experience", "Cultural insights", "Local market knowledge"]'::jsonb,
 '["Food safety guidelines", "Cultural context", "Dietary accommodation"]'::jsonb,
 'Grand Indonesia MRT Station', 3.2, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Eko Bandung Explorer's Experience (Local Tour Guide - Bandung)  
(8, gen_random_uuid(), 'Bandung Tea Plantation & Factory Tour', 'bandung-tea-plantation-factory-tour',
 'Explore Bandung highland tea plantations and learn traditional tea processing. Visit colonial-era tea factories and enjoy fresh mountain air.',
 'Highland tea plantation tour with traditional processing and colonial history.',
 27, 1, 3, 4, 320000.00, 'IDR', 5, 12, 2, 'easy',
 '["bandung-tea-plantation.jpg", "tea-processing.jpg", "highland-view.jpg"]'::jsonb,
 '["Professional guide", "Tea factory tour", "Tea tasting session", "Transportation", "Light refreshments"]'::jsonb,
 '["Lunch", "Shopping", "Tips", "Personal expenses"]'::jsonb,
 'Dago Pakar area, Bandung', -6.8650, 107.5950, true, false, 4.5, 67, 94, 
 '{"specialization": "Highland Tourism", "history_knowledge": "Colonial Era"}'::jsonb,
 '["Tea knowledge", "Historical insights", "Scenic photography spots"]'::jsonb,
 '["Transportation", "Tea samples", "Historical documentation"]'::jsonb,
 'Bandung city center', 12.8, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Lestari Yogya Arts's Experience (Photographer - Yogyakarta)
(9, gen_random_uuid(), 'Yogyakarta Traditional Arts Photo Session', 'yogyakarta-traditional-arts-photo-session',
 'Professional photo session showcasing Javanese traditional arts. Wear traditional costumes and pose with cultural artifacts in authentic settings.',
 'Traditional Javanese arts photography with authentic costumes and cultural props.',
 28, 2, 6, 3, 425000.00, 'IDR', 3, 6, 1, 'easy',
 '["yogya-traditional-arts.jpg", "javanese-costume.jpg", "cultural-portrait.jpg"]'::jsonb,
 '["Professional photographer", "Traditional costume rental", "Cultural props", "Edited photos (20)", "Cultural guide"]'::jsonb,
 '["Transportation", "Additional photos", "Print copies", "Makeup artist"]'::jsonb,
 'Taman Sari Water Castle, Yogyakarta', -7.8053, 110.3587, true, true, 4.8, 43, 61, 
 '{"photography_style": "Cultural Portrait", "costume_collection": 15}'::jsonb,
 '["20 edited photos", "Cultural context", "Traditional costume experience"]'::jsonb,
 '["Professional camera", "Traditional costumes", "Cultural props", "Lighting equipment"]'::jsonb,
 'Taman Sari Water Castle', 1.5, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Putu Lombok Adventure's Experience (Local Tour Guide - Lombok)
(10, gen_random_uuid(), 'Lombok Waterfalls & Village Trek', 'lombok-waterfalls-village-trek',
 'Trek through traditional Sasak villages to discover hidden waterfalls. Experience local village life and swim in crystal-clear natural pools.',
 'Village trekking adventure to hidden waterfalls with authentic Sasak culture immersion.',
 29, 1, 4, 10, 380000.00, 'IDR', 6, 10, 2, 'moderate',
 '["lombok-waterfall.jpg", "sasak-village.jpg", "traditional-life.jpg"]'::jsonb,
 '["Professional guide", "Village visit", "Waterfall access", "Traditional lunch", "Cultural demonstration"]'::jsonb,
 '["Transportation to start point", "Personal expenses", "Tips", "Swimming gear"]'::jsonb,
 'Senaru Village, North Lombok', -8.3405, 116.4073, true, false, 4.7, 78, 115, 
 '{"cultural_expertise": "Sasak Traditions", "trekking_experience": "12 years"}'::jsonb,
 '["Cultural immersion", "Waterfall swimming", "Traditional lunch", "Village insights"]'::jsonb,
 '["Trekking equipment", "First aid", "Cultural translation"]'::jsonb,
 'Senaru Village', 8.5, 'moderate', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Indra Surabaya Heritage's Experience (Local Tour Guide - Surabaya)
(11, gen_random_uuid(), 'Surabaya Heroes Monument & Historic District', 'surabaya-heroes-monument-historic-district',
 'Explore Surabaya historic significance in Indonesia independence. Visit Heroes Monument, historic buildings, and learn about the Battle of Surabaya.',
 'Historical tour of Surabaya independence sites and Heroes Monument.',
 30, 1, 3, 5, 225000.00, 'IDR', 4, 15, 2, 'easy',
 '["heroes-monument.jpg", "surabaya-historic.jpg", "independence-sites.jpg"]'::jsonb,
 '["Professional guide", "Monument entrance", "Historical documentation", "Local transportation"]'::jsonb,
 '["Lunch", "Shopping", "Tips", "Personal expenses"]'::jsonb,
 'Heroes Monument (Tugu Pahlawan), Surabaya', -7.2459, 112.7378, true, false, 4.4, 52, 73, 
 '{"specialization": "Independence History", "guide_certification": "National Heritage"}'::jsonb,
 '["Historical knowledge", "Independence stories", "Local insights"]'::jsonb,
 '["Historical references", "Transportation", "Monument access"]'::jsonb,
 'Surabaya city center', 5.8, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Dika Lens Studio's Experience (Photographer - Jakarta)
(12, gen_random_uuid(), 'Jakarta Modern Architecture Photo Tour', 'jakarta-modern-architecture-photo-tour',
 'Photography tour of Jakarta modern skyline and architectural marvels. Capture iconic buildings from unique angles with professional guidance.',
 'Professional architecture photography tour of Jakarta modern landmarks.',
 11, 2, 7, 1, 550000.00, 'IDR', 4, 8, 2, 'easy',
 '["jakarta-skyline.jpg", "modern-architecture.jpg", "urban-photography.jpg"]'::jsonb,
 '["Professional photographer guide", "Photography tips", "Best angle spots", "Edited sample photos (10)"]'::jsonb,
 '["Camera equipment", "Transportation", "Meals", "Additional photo editing"]'::jsonb,
 'Bundaran Hotel Indonesia, Jakarta', -6.1944, 106.8231, true, true, 4.6, 38, 45, 
 '{"photography_specialty": "Architecture", "equipment_expertise": true}'::jsonb,
 '["Photography techniques", "Composition guidance", "10 sample edited photos"]'::jsonb,
 '["Professional guidance", "Location access", "Photography tips"]'::jsonb,
 'Grand Indonesia area', 6.2, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Wayan Combo Tours's Experience (Combo Guide - Bali)
(13, gen_random_uuid(), 'Bali Cultural Immersion + Photography Package', 'bali-cultural-immersion-photography-package',
 'Complete Bali experience combining cultural tour with professional photography. Visit temples, witness ceremonies, and get stunning photos.',
 'Ultimate Bali cultural tour with professional photography documentation.',
 12, 3, 11, 2, 750000.00, 'IDR', 7, 6, 2, 'easy',
 '["bali-culture-photo.jpg", "temple-ceremony.jpg", "cultural-portrait.jpg"]'::jsonb,
 '["Professional guide-photographer", "Temple visits", "Cultural ceremony", "30 edited photos", "Traditional costume"]'::jsonb,
 '["Transportation", "Meals", "Temple donations", "Additional photos"]'::jsonb,
 'Ubud traditional market', -8.5069, 115.2625, true, true, 4.9, 124, 178, 
 '{"dual_expertise": "Guide + Photography", "cultural_knowledge": "Balinese Hindu"}'::jsonb,
 '["Cultural insights", "30 professional photos", "Ceremony participation", "Traditional experience"]'::jsonb,
 '["Professional camera", "Cultural access", "Traditional props", "Ceremony guidance"]'::jsonb,
 'Ubud art district', 12.5, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Indonesia Travel Pro's Additional Experience (Trip Planner - Multi-city)
(14, gen_random_uuid(), 'Java Heritage Circuit Planning', 'java-heritage-circuit-planning',
 'Comprehensive trip planning for Java cultural heritage circuit. Cover Jakarta, Bandung, Yogyakarta, and Solo with detailed itinerary.',
 'Professional Java heritage circuit planning with cultural and historical focus.',
 14, 4, 14, 1, 2500000.00, 'IDR', 6, 10, 1, 'easy',
 '["java-heritage.jpg", "cultural-circuit.jpg", "trip-planning.jpg"]'::jsonb,
 '["Professional consultation", "Detailed 7-day itinerary", "Accommodation booking", "Transportation arrangement", "24/7 support"]'::jsonb,
 '["Actual travel costs", "Meals during trip", "Personal expenses", "Additional services"]'::jsonb,
 'Virtual Meeting (Online Consultation)', 0.0, 0.0, true, false, 4.9, 67, 89, 
 '{"specialization": "Java Heritage", "network": "Multi-city partners"}'::jsonb,
 '["Complete itinerary", "Booking confirmations", "Local recommendations", "Emergency support"]'::jsonb,
 '["Planning software", "Partner network", "Local guides coordination"]'::jsonb,
 'Online Consultation', 0.0, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Made Ngurah's Additional Experience (Photographer - Bali)
(15, gen_random_uuid(), 'Bali Wedding Pre-shoot Package', 'bali-wedding-pre-shoot-package',
 'Romantic pre-wedding photography session at Bali most scenic locations. Includes Tegallalang rice terraces, temple, and beach sunset.',
 'Complete Bali pre-wedding photography with multiple scenic locations.',
 9, 2, 8, 2, 1200000.00, 'IDR', 8, 4, 2, 'easy',
 '["bali-prewedding.jpg", "rice-terrace-couple.jpg", "beach-sunset-couple.jpg"]'::jsonb,
 '["Professional photographer", "3 locations shoot", "50 edited photos", "Makeup artist", "Transportation", "Props"]'::jsonb,
 '["Outfits", "Additional locations", "Extra photos", "Album printing"]'::jsonb,
 'Tegallalang Rice Terrace, Bali', -8.4357, 115.2827, true, true, 4.8, 95, 134, 
 '{"wedding_specialty": true, "portfolio_experience": "200+ couples"}'::jsonb,
 '["50 edited photos", "Multiple locations", "Professional makeup", "Romantic concepts"]'::jsonb,
 '["Professional camera equipment", "Lighting", "Props", "Transportation"]'::jsonb,
 'Beach location (sunset)', 25.3, 'easy', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Reset sequence to match the highest ID
SELECT setval('experiences_id_seq', (SELECT MAX(id) FROM experiences));
