-- Insert Story Comments
-- This file seeds the story_comments table with GenZ-friendly comments

INSERT INTO story_comments (id, story_id, user_id, parent_id, content, is_approved, created_at, updated_at) VALUES
-- Story 1: Hidden Temples in Ubud (5 comments)
(1, 1, 2, NULL, 'OMG this is giving me ALL the spiritual vibes! 🙏✨ Ubud is literally on my bucket list now!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(2, 1, 3, NULL, 'Your photos are absolutely STUNNING bestie! 📸 The morning mist shots are chef''s kiss! 💋', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(3, 1, 4, NULL, 'No cap, these hidden temples look more magical than anything on Instagram! When''s our girls trip? 👯‍♀️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(4, 1, 5, 1, 'RIGHT?! I''m literally booking my flight to Bali after reading this! The spiritual energy is calling me! 🌸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(5, 1, 6, NULL, 'The way you described the cultural significance had me crying happy tears! 😭💫 This is what authentic travel looks like!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 2: Jakarta Street Food (8 comments)
(6, 2, 1, NULL, 'Yo the street food scene looks INSANE! 🔥🍜 Which area slapped the hardest for authentic eats?', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(7, 2, 3, NULL, 'Kerak Telor hits different when done right! 🍳 Your description made my mouth water fr!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(8, 2, 4, NULL, 'Planning Jakarta food tour next month and this is my BIBLE now! 📖 Drop more recommendations please! 🙏', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(9, 2, 5, 6, 'Honestly Sabang Street at midnight is where the magic happens! The late night energy is unmatched! 🌙✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(10, 2, 7, NULL, 'That Soto Betawi description got me EMOTIONAL! 😭 I need that recipe ASAP! Share the secrets bestie!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(11, 2, 8, 4, 'Try Es Campur too! And don''t sleep on the Rujak Cingur - it''s an acquired taste but SO worth it! 🥗', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(12, 2, 9, NULL, 'Your food photography is giving professional vibes! 📸 What camera setup are you using?', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(13, 2, 10, NULL, 'Reading this made me so homesick for Jakarta! 😢 Nothing beats authentic Indonesian street food! 🇮🇩', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 3: Yogyakarta Royal Heritage (12 comments)
(14, 3, 1, NULL, 'The Sultan Palace sounds absolutely INCREDIBLE! 👑 Did you catch any traditional ceremonies while you were there?', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(15, 3, 2, NULL, 'Yogya''s cultural heritage is just *chef''s kiss* 💋 Thanks for sharing the royal tea! ☕️👑', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(16, 3, 4, NULL, 'Traditional dances in the palace courtyard? I''m LIVING for this authentic cultural experience! 💃✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(17, 3, 5, 14, 'YES! Witnessed a wedding ceremony there and literally CRIED at how beautiful it was! 😭👰💫', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(18, 3, 6, NULL, 'Taman Sari is giving fairytale vibes! 🏰 The underground tunnels sound like something from a movie!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(19, 3, 7, NULL, 'The architectural details you described are absolutely fascinating! 🏛️ Living history hits different!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(20, 3, 8, NULL, 'How long should I budget for the full palace experience? Planning my cultural immersion day! 📅', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(21, 3, 9, 20, 'Honestly spend the WHOLE day there! 🕐 3-4 hours minimum but you could easily do 6+ hours and not be bored!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(22, 3, 11, NULL, 'The living museum concept is absolutely GENIUS! 🧠 History that''s still alive and breathing!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(23, 3, 12, NULL, 'Did you try any royal-inspired cuisine? 🍽️ I''m curious about traditional palace food!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(24, 3, 13, NULL, 'Your storytelling transported me straight to those palace corridors! ✨ I felt like I was walking with you!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(25, 3, 14, 23, 'Gudeg Yu Djum serves royal-inspired dishes and it''s AMAZING! 🍛 Traditional flavors with palace heritage!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 4: Bandung Coffee Culture (15 comments)
(26, 4, 1, NULL, 'As a coffee addict, this story is EVERYTHING! ☕️💫 Which spot had the most fire beans?', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(27, 4, 2, NULL, 'Bandung''s coffee scene is SO underrated! 😤 More people need to know about this hidden gem!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(28, 4, 3, NULL, 'Traditional warung meets third-wave coffee? That fusion sounds absolutely INCREDIBLE! 🔥☕️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(29, 4, 4, 26, 'Warung Kopi Purnama for that authentic traditional vibe, Common Grounds for modern specialty! Both SLAP! 👌', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(30, 4, 5, NULL, 'I NEED those coffee bean recommendations! 🫘 Planning my own Bandung coffee pilgrimage!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(31, 4, 6, NULL, 'The passion you described in the baristas is what makes Indonesian coffee culture so special! ❤️☕️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(32, 4, 7, 30, 'Kopilaku roasters are INSANE! 🤯 Their Aceh and Toraja single origins will change your life!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(33, 4, 8, NULL, 'Your latte art photos are giving me LIFE! 📸 These baristas are literally artists!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(34, 4, 9, NULL, 'How does Bandung compare to global coffee capitals like Melbourne or Seattle? 🌍☕️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(35, 4, 10, 34, 'It''s more intimate and personal tbh! Every cup comes with stories and genuine passion! 💫', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(36, 4, 11, NULL, 'The traditional coffee ritual sounds SO meditative! 🧘‍♀️ I need this zen energy in my life!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(37, 4, 12, NULL, 'Your storytelling captured the SOUL of coffee culture perfectly! ☕️✨ I''m obsessed!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(38, 4, 13, NULL, 'What''s the best time to experience both traditional and modern coffee scenes? ⏰', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(39, 4, 14, 38, 'Early morning for warung vibes, afternoon for modern cafe energy! Both hit different! 🌅🌆', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(40, 4, 15, NULL, 'This article just convinced me to make Bandung my next coffee adventure destination! ✈️☕️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 5: Lombok Secret Beaches (22 comments)
(41, 5, 1, NULL, 'These hidden beaches are absolutely PRISTINE! 🏖️✨ How challenging was the hiking situation?', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(42, 5, 2, NULL, 'Lombok staying underrated while everyone crowds Bali! 😤 These gems need more recognition!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(43, 5, 3, NULL, 'WAIT Pink Beach is actually PINK?! 💗 I thought it was just the name! Mind = blown! 🤯', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(44, 5, 4, 41, 'About 2 hours of moderate hiking but bestie it''s SO worth every step! The payoff is UNREAL! 🥾⛰️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(45, 5, 5, 43, 'YES! The coral fragments literally make the sand PINK! Nature is absolutely incredible! �coral🌸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(46, 5, 6, NULL, 'Your underwater shots are giving National Geographic vibes! 📸🐠 That water clarity is INSANE!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(47, 5, 7, NULL, 'Can you camp on these beaches overnight? 🏕️ I''m imagining sunrise on pink sand and CRYING! 😭', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(48, 5, 8, 47, 'Some beaches allow camping but bring your own gear! Definitely check with locals first for safety! 🏕️✅', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(49, 5, 9, NULL, 'That sunset photo literally took my BREATH AWAY! 🌅 Perfect timing and composition!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(50, 5, 10, NULL, 'How do you access these secret spots? Is a local guide absolutely necessary? 🗺️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(51, 5, 11, 50, 'Local guide is HIGHLY recommended! They know safe paths and all the hidden gems! 👥🗺️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(52, 5, 12, NULL, 'This is making me skip crowded Gili Islands completely! Secret beaches over tourist traps! 🏝️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(53, 5, 13, NULL, 'The crystal clear water looks PERFECT for snorkeling! 🤿 Any specific spots you recommend?', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(54, 5, 14, 53, 'Tangsi Beach has INCREDIBLE coral gardens literally 50 meters from shore! Marine life paradise! 🐠🪸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(55, 5, 15, NULL, 'Your adventure spirit is SO inspiring! ✨ These photos belong in travel magazines fr! 📸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(56, 5, 16, NULL, 'Best season for visiting these beaches? Weather and hiking conditions? 🌤️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(57, 5, 17, 56, 'April to September is PERFECT! Dry season means less rain and calmer seas for hiking! ☀️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(58, 5, 18, NULL, 'This untouched beauty is what makes Indonesia so special! Perfectly documented! 🇮🇩💎', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(59, 5, 19, NULL, 'Any accommodation nearby or is this strictly day trip territory? 🏠', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(60, 5, 20, 59, 'Mostly day trips but some locals offer homestays in nearby villages! Authentic experience! 🏡', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(61, 5, 21, NULL, 'This story single-handedly convinced me to choose Lombok over Bali! PERIODT! 💅✈️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(62, 5, 22, NULL, 'Your descriptions made me feel like I was already walking on that pink sand! ✨🏖️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 6: Surabaya Historical Journey (9 comments)
(63, 6, 1, NULL, 'Surabaya''s independence history is SO important! 🇮🇩 Thanks for putting respect on this city''s name!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(64, 6, 2, NULL, 'Heroes Monument hits DIFFERENT when you know the history! 🏛️ Did you explore the museum inside?', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(65, 6, 3, 64, 'YES! The museum context about Battle of Surabaya gave me actual CHILLS! So powerful! 💪', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(66, 6, 4, NULL, 'Colonial architecture in Surabaya is absolutely STUNNING! 🏛️ Any other buildings I should add to my list?', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(67, 6, 5, 66, 'Majapahit Hotel and Old Town area are GORGEOUS! Colonial vibes with so much history! 🏨✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(68, 6, 6, NULL, 'Your historical storytelling brought the past to LIFE! 📚 This is how history should be taught!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(69, 6, 7, NULL, 'Are there good historical walking tours in Surabaya? 🚶‍♀️ I want the full experience!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(70, 6, 8, 69, 'City tourism office has guided historical tours on weekends! Perfect for deep diving into history! 🗓️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(71, 6, 9, NULL, 'Surabaya deserves WAY more recognition as a historical destination! This article is everything! 👑', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 7: Jakarta Modern Art Scene (18 comments)
(72, 7, 1, NULL, 'Jakarta''s art scene is UNHINGED and I''m here for it! 🎨🔥 Which gallery blew your mind the most?', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(73, 7, 2, NULL, 'The street art you described sounds absolutely INSANE! 🎨 Drop the locations bestie!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(74, 7, 3, NULL, 'Traditional meets contemporary? That sounds like the perfect cultural fusion! ✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(75, 7, 4, 72, 'National Gallery was mind-blowing but honestly the warehouse spaces in Kemang hit different! 🏢', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(76, 7, 5, NULL, 'The way artists are tackling social issues through art is SO powerful! 💪 This is what art should do!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(77, 7, 6, 73, 'North Jakarta industrial areas have the most incredible murals! Political commentary that hits HARD! 💯', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(78, 7, 7, NULL, 'Artist collectives supporting each other is beautiful! 🤝 That''s what community looks like!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(79, 7, 8, NULL, 'Gallery openings as community events? I LOVE that approach to art! 🎉', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(80, 7, 9, NULL, 'The digital projections with gamelan music combo sounds absolutely REVOLUTIONARY! 🎵🎨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(81, 7, 10, NULL, 'Are there any art walks or tours that showcase the underground scene? 🚶‍♀️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(82, 7, 11, 81, 'Check out Jakarta Biennale events - they organize incredible art walks through creative spaces! 🎨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(83, 7, 12, NULL, 'Indonesian artists getting global recognition while staying culturally rooted is ICONIC! 🌍', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(84, 7, 13, NULL, 'The environmental art installations using waste materials sound incredibly impactful! ♻️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(85, 7, 14, NULL, 'Your description of the creative energy made me feel like I was in those galleries! ✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(86, 7, 15, NULL, 'Adding Jakarta art scene to my cultural bucket list RIGHT NOW! 📝', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(87, 7, 16, NULL, 'The political courage in these artworks is absolutely inspiring! 💪', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(88, 7, 17, NULL, 'Contemporary art that addresses local issues while appealing globally? Chef''s kiss! 💋', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(89, 7, 18, NULL, 'This article convinced me that Jakarta is Southeast Asia''s hidden art capital! 👑', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 8: Bali Rice Terrace Photography (11 comments)
(90, 8, 1, NULL, 'These rice terrace shots are giving me LIFE! 📸✨ 4AM wake up was so worth it!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(91, 8, 2, NULL, 'Jatiluwih being UNESCO heritage makes so much sense! 🌾 1000 years of rice cultivation is INSANE!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(92, 8, 3, NULL, 'The mirror reflections in your photos are absolutely STUNNING! 💫 Perfect composition!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(93, 8, 4, NULL, 'Meeting Pak Made and learning about Subak system sounds incredibly meaningful! 🌾👨‍🌾', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(94, 8, 5, NULL, 'Your photography tips are GOLD! 📸 Polarizing filter noted for my Bali trip!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(95, 8, 6, NULL, 'The way you captured different seasons of rice farming is absolutely brilliant! 🌱', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(96, 8, 7, NULL, 'Tegallalang vs Jatiluwih comparison is super helpful! 🙏 Planning my photo spots!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(97, 8, 8, 95, 'Definitely shoot in RAW! The dynamic range in these landscapes is absolutely incredible! 📸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(98, 8, 9, NULL, 'The respect for farming communities in your writing is beautiful! 💚 Sustainable tourism done right!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(99, 8, 10, NULL, 'Golden hour lighting on those terraces must have been absolutely MAGICAL! ✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(100, 8, 11, NULL, 'This makes me want to wake up at 4AM for photography and I HATE mornings! 😅📸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 9: Yogyakarta Traditional Batik Making (25 comments)
(101, 9, 1, NULL, 'The batik workshop experience sounds absolutely TRANSFORMATIVE! 🎨✨ Bu Sari seems incredible!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(102, 9, 2, NULL, 'Every motif having symbolic meaning just blew my MIND! 🤯 Indonesian culture is so deep!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(103, 9, 3, NULL, 'The meditative aspect of batik-making sounds like therapy! 🧘‍♀️ I need this in my life!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(104, 9, 4, NULL, 'Batik patterns being banned during colonialism but preserved in secret? POWERFUL! 💪', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(105, 9, 5, NULL, 'Hand-drawn vs stamped vs printed explanation is so helpful! 🎨 Quality makes sense now!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(106, 9, 6, 101, '40 years of experience shows in every stroke! Master craftspeople deserve ALL the respect! 🙏', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(107, 9, 7, NULL, 'Natural dye processes sound incredible! 🌿 Sustainable practices from centuries ago!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(108, 9, 8, NULL, 'Young artists innovating while respecting tradition is BEAUTIFUL! 💫', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(109, 9, 9, NULL, 'The economics you explained really opened my eyes! 👀 Artisans deserve fair wages!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(110, 9, 10, NULL, 'Parang and kawung patterns having deep meanings is absolutely fascinating! 🌸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(111, 9, 11, NULL, 'Where can I sign up for a batik workshop? This experience sounds ESSENTIAL! ✋', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(112, 9, 12, 111, 'Taman Sari area has amazing workshops! Look for Bu Sari''s studio - she''s legendary! 🎨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(113, 9, 13, NULL, 'The way you described the cultural resilience through batik made me emotional! 😭💚', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(114, 9, 14, NULL, 'Weeks or months for one piece? The dedication and skill is absolutely mind-blowing! ⏰', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(115, 9, 15, NULL, 'This article changed my entire perspective on fast fashion vs traditional crafts! 👗', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(116, 9, 16, NULL, 'The meditation aspect while creating art sounds incredibly grounding! 🧘‍♀️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(117, 9, 17, NULL, 'Cultural preservation through daily practice is so much more powerful than museums! 💪', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(118, 9, 18, NULL, 'Your 3-day workshop journey sounds like a life-changing experience! ✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(119, 9, 19, NULL, 'The way batik connects to Javanese philosophy is absolutely beautiful! 🌸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(120, 9, 20, NULL, 'Indigo and soga bark creating those deep colors naturally is AMAZING! 🎨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(121, 9, 21, NULL, 'This makes me want to learn traditional crafts and slow down my creative process! 🎨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(122, 9, 22, NULL, 'The intergenerational knowledge sharing you described is so precious! 👵👶', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(123, 9, 23, NULL, 'Your storytelling made me feel every step of the batik creation process! ✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(124, 9, 24, NULL, 'This is what authentic cultural immersion looks like! Not just observing but LEARNING! 📚', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(125, 9, 25, NULL, 'I''m booking my Yogyakarta trip specifically for this batik experience now! ✈️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 10: Bandung Factory Outlets Shopping (7 comments)
(126, 10, 1, NULL, 'Sustainable fashion at factory outlets? This is GENIUS! 🛍️♻️ Why didn''t I think of this before?', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(127, 10, 2, NULL, 'Rumah Mode sounds like shopping PARADISE! 🛍️✨ Multiple floors of amazing finds!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(128, 10, 3, NULL, 'Designer jeans for $15? I''m BOOKING MY FLIGHT! ✈️👖', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(129, 10, 4, NULL, 'The distro culture you described sounds so unique! 🏪 Independent curated fashion!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(130, 10, 5, NULL, 'Industrial-grade quality at affordable prices makes total sense! 💡 Smart shopping!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(131, 10, 6, NULL, 'Meeting local designers and hearing their stories sounds inspiring! 👗✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(132, 10, 7, NULL, 'This completely changed my relationship with fast fashion! Sustainable shopping wins! 💚', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 11: Lombok Traditional Sasak Village (19 comments)
(133, 11, 1, NULL, 'The traditional Sasak architecture sounds absolutely INCREDIBLE! 🏠✨ Smart design for tropical living!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(134, 11, 2, NULL, 'Community house building with just natural materials? This is AMAZING! 🤝🏠', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(135, 11, 3, NULL, 'The consensus decision-making sounds like such a beautiful way to live! 💫', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(136, 11, 4, NULL, 'Traditional weaving techniques thousands of years old? My mind is BLOWN! 🧵', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(137, 11, 5, NULL, 'The way they balance tradition with modern needs is inspiring! 🌟', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(138, 11, 6, NULL, 'Sustainable agriculture working with natural cycles is GENIUS! 🌱', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(139, 11, 7, NULL, 'The hospitality you described made my heart warm! 💚 True community spirit!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(140, 11, 8, NULL, 'Children playing with handmade toys sounds so pure! 🧸 Simple happiness!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(141, 11, 9, NULL, 'This experience sounds life-changing! Connection over consumption is everything! ✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(142, 11, 10, NULL, 'The intergenerational dialogue about preserving culture is beautiful! 👵👶', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(143, 11, 11, NULL, 'How do I visit respectfully? I want to learn without being intrusive! 🙏', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(144, 11, 12, 143, 'Go through local guides, dress modestly, and participate genuinely! Respect is key! 💯', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(145, 11, 13, NULL, 'The grass roof and bamboo construction sounds incredibly sustainable! 🏠🌿', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(146, 11, 14, NULL, 'This redefined my understanding of wealth and happiness completely! 💎', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(147, 11, 15, NULL, 'Traditional medicine plants in forest preservation is so smart! 🌿💊', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(148, 11, 16, NULL, 'The village youth navigating tradition and modernity sounds fascinating! 🌟', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(149, 11, 17, NULL, 'Your writing made me question everything about modern living! 🤔✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(150, 11, 18, NULL, 'This isn''t just tourism - it''s a masterclass in sustainable living! 🎓', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(151, 11, 19, NULL, 'I need this community connection in my life! Modern isolation hits different now! 💚', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 12: Surabaya Culinary Night Market (16 comments)
(152, 12, 1, NULL, 'Surabaya night market energy sounds ELECTRIC! ⚡🍜 Pasar Genteng is going on my list!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(153, 12, 2, NULL, 'Rawon looking intimidating but tasting amazing is such a mood! 🖤🍲', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(154, 12, 3, NULL, 'The black soup description made me SO curious! Keluak nuts sound fascinating! 🥜', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(155, 12, 4, NULL, 'Lontong Balap as culinary ART? I''m here for this food appreciation! 🎨🍛', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(156, 12, 5, NULL, 'Rujak Cingur took courage to try? Respect for being adventurous! 💪🥗', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(157, 12, 6, NULL, '40 years same recipe and regular customers bringing grandchildren? ICONIC! 👵', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(158, 12, 7, NULL, 'Night markets as social media of previous generations is BRILLIANT insight! 💡', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(159, 12, 8, NULL, 'Complete meal for under $3 with restaurant-quality flavors? Sign me UP! 💸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(160, 12, 9, NULL, 'Es Campur with colorful jellies sounds like happiness in a bowl! 🍧🌈', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(161, 12, 10, NULL, 'Markets staying open until dawn serving different shifts is beautiful continuity! 🌅', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(162, 12, 11, NULL, 'The community gathering around food preparation sounds so wholesome! 🤝', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(163, 12, 12, NULL, 'Your description of vendors as culinary masters is perfect! 👨‍🍳✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(164, 12, 13, NULL, 'Sate Klopo with coconut coating sounds absolutely DIVINE! 🥥🍢', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(165, 12, 14, NULL, 'Food connecting you to history and community is everything! 💚', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(166, 12, 15, NULL, 'This made me SO hungry for authentic Indonesian flavors! 🤤', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(167, 12, 16, NULL, 'Your night market adventure completely changed my perspective on street food! 🌟', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 13: Jakarta Hidden Neighborhoods (13 comments) 
(168, 13, 1, NULL, 'Kemang''s blend of traditional and contemporary sounds PERFECT! 🏙️✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(169, 13, 2, NULL, 'Art scene in converted warehouses? Jakarta''s creativity is UNMATCHED! 🎨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(170, 13, 3, NULL, 'Kota Tua being where independence was declared gave me CHILLS! 🇮🇩', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(171, 13, 4, NULL, 'Living history with elderly residents sharing memories is precious! 👵💎', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(172, 13, 5, NULL, 'Menteng giving European garden city vibes in Jakarta? Mind blown! 🌳', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(173, 13, 6, NULL, 'Each neighborhood having distinct personality is fascinating! 🏘️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(174, 13, 7, NULL, 'Different food scenes in each area shows incredible diversity! 🍜', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(175, 13, 8, NULL, 'Walking/cycling revealing hidden layers is the BEST way to explore! 🚲', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(176, 13, 9, NULL, 'Multi-generational families maintaining community connections is beautiful! 💚', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(177, 13, 10, NULL, 'Strong neighborhood identity in a megacity is surprisingly heartwarming! 🏠', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(178, 13, 11, NULL, 'Street art and hidden temples in the same neighborhood? Jakarta is wild! 🎨🛕', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(179, 13, 12, NULL, 'This convinced me to explore beyond tourist sites everywhere I travel! 🗺️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(180, 13, 13, NULL, 'The soul of Jakarta living in these hidden communities is beautiful! 💫', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 14: Bali Volcano Hiking Adventure (21 comments)
(181, 14, 1, NULL, 'Mount Batur sunrise hike sounds absolutely EPIC! 🌋🌅 2AM wake up is rough but worth it!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(182, 14, 2, NULL, 'International hikers united by shared adventure goal is beautiful! 🌍🥾', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(183, 14, 3, NULL, 'Hiking an ACTIVE volcano that erupted in 2000? That''s incredible and terrifying! 🌋', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(184, 14, 4, NULL, 'Steam vents and sulfur deposits must have been surreal to witness! 💨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(185, 14, 5, NULL, 'Crying at the summit sunrise over volcanic caldera sounds life-changing! 😭🌅', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(186, 14, 6, NULL, 'Cooking breakfast with volcanic steam is the coolest thing EVER! 🍳🌋', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(187, 14, 7, NULL, 'Sliding down volcanic sand slopes sounds like nature''s playground! 🏔️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(188, 14, 8, NULL, 'The biodiversity from desert to tropical vegetation is amazing! 🌵🌴', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(189, 14, 9, NULL, 'Connections made through shared adventure lasting afterwards is precious! 🤝', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(190, 14, 10, NULL, 'Spiritual aspect of standing on active volcano is profound! ✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(191, 14, 11, NULL, 'What time should I start the hike? Planning my volcano adventure! 🕐', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(192, 14, 12, 191, '2AM start is standard! Gives you time to reach summit before sunrise! Early but magical! 🌅', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(193, 14, 13, NULL, 'The transformative experience pushing comfort zones is inspiring! 💪', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(194, 14, 14, NULL, 'Warm layers for summit? Noted! Cold at altitude surprises many people! 🧥', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(195, 14, 15, NULL, 'Lake Batur sparkling below with Mount Agung backdrop sounds STUNNING! 🏔️💎', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(196, 14, 16, NULL, 'Your description made me feel the adrenaline and magic! 🔥', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(197, 14, 17, NULL, 'Safety with reputable guides is crucial for active volcano! Good advice! ⚠️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(198, 14, 18, NULL, 'The earth''s power beneath your feet must be humbling and empowering! 🌍', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(199, 14, 19, NULL, 'This adventure is going straight to my Bali bucket list! 📝', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(200, 14, 20, NULL, 'Your enthusiasm for pushing limits is absolutely infectious! 🚀', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(201, 14, 21, NULL, 'Mount Batur experience as life perspective changer resonates deeply! 🌋💭', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 15: Yogyakarta Underground Music Scene (14 comments)
(202, 15, 1, NULL, 'Yogya''s music scene blending gamelan with punk rock? That sounds REVOLUTIONARY! 🎵🔥', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(203, 15, 2, NULL, 'The intimacy between artists and audience in small venues is magic! 🎤✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(204, 15, 3, NULL, 'DIY culture with bedroom studios producing professional quality is inspiring! 🏠🎵', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(205, 15, 4, NULL, 'Music as social commentary and political expression is SO powerful! 💪', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(206, 15, 5, NULL, 'Gamelan masters collaborating with indie musicians sounds incredible! 🎶', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(207, 15, 6, NULL, 'The collaborative spirit over competition is beautiful! 🤝 Real community!', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(208, 15, 7, NULL, 'Toko Oen supporting local music for decades is legendary! 🏪🎵', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(209, 15, 8, NULL, 'Cross-disciplinary projects with visual artists and poets sounds amazing! 🎨📝', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(210, 15, 9, NULL, 'Engaged audiences who actually LISTEN is rare and precious! 👂✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(211, 15, 10, NULL, 'Affordable concert tickets making art accessible is everything! 💰🎵', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(212, 15, 11, NULL, 'Famous Indonesian musicians starting in Yogya''s underground is iconic! 🌟', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(213, 15, 12, NULL, 'Which venues should I check out for the best underground shows? 🎤', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(214, 15, 13, 213, 'Toko Oen is classic, but also check out Via-Via and smaller art collectives! 🏪', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(215, 15, 14, NULL, 'The future of Indonesian music being created in real time is EXCITING! 🚀', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 16: Bandung Creative City Tour (12 comments)
(216, 16, 1, NULL, 'UNESCO Creative City status with actual infrastructure support? Goals! 🏛️✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(217, 16, 2, NULL, 'Converted factory spaces for creative collaboration sound INCREDIBLE! 🏭🎨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(218, 16, 3, NULL, 'Traditional materials with contemporary forms getting international recognition! 🌍', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(219, 16, 4, NULL, 'Economic development through cultural preservation is brilliant! 💡💰', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(220, 16, 5, NULL, 'Collaborative business approach where everyone succeeds together is beautiful! 🤝', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(221, 16, 6, NULL, 'Universities integrated with creative economy is smart education! 🎓', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(222, 16, 7, NULL, 'Building global brands while staying culturally rooted is inspiring! 🌍🌿', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(223, 16, 8, NULL, 'International creative networks through UNESCO are amazing opportunities! 🌐', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(224, 16, 9, NULL, 'Technology enhancing rather than replacing tradition is perfect balance! ⚖️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(225, 16, 10, NULL, 'Sustainability focus in creative industries is the future! ♻️✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(226, 16, 11, NULL, 'This model should be studied and replicated everywhere! 📚', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(227, 16, 12, NULL, 'Bandung representing the future of creative cities is so exciting! 🚀', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 17: Lombok Diving Paradise (28 comments)
(228, 17, 1, NULL, 'Manta rays with 4-meter wingspan? I''m SCREAMING underwater too! 🤿🐋', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(229, 17, 2, NULL, 'Pristine coral reefs compared to damaged tourist destinations is precious! 🪸💎', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(230, 17, 3, NULL, 'Wall dives with incredible visibility sound absolutely STUNNING! 🏔️💙', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(231, 17, 4, NULL, 'Night dives revealing different creatures sound magical! 🌙🐙', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(232, 17, 5, NULL, 'Bio-luminescent plankton lighting up when you move? INCREDIBLE! ✨🌊', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(233, 17, 6, NULL, 'Macro photography opportunities with colorful nudibranchs sound amazing! 📸🐌', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(234, 17, 7, NULL, 'Professional dive operators with conservation focus is reassuring! 🤿💚', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(235, 17, 8, NULL, 'Coral restoration projects show real environmental commitment! 🪸🌱', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(236, 17, 9, NULL, 'Warm water temps and 30+ meter visibility year-round? Paradise! 🌡️👁️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(237, 17, 10, NULL, 'Perfect learning conditions for certification courses makes sense! 📚🤿', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(238, 17, 11, NULL, 'Affordable world-class diving compared to touristy destinations is incredible! 💰', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(239, 17, 12, NULL, 'What certification level do you need for the best dive sites? 🤿', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(240, 17, 13, 239, 'Open Water is fine for most sites! Advanced for deeper walls and stronger currents! 📊', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(241, 17, 14, NULL, 'Tiny seahorses hiding in coral branches must be adorable! 🐴🪸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(242, 17, 15, NULL, 'Mandarin fish mating dances at sunset sound incredibly special! 🐠💃', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(243, 17, 16, NULL, 'Multiple dives per day at fraction of other costs is unbeatable value! 🤿💯', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(244, 17, 17, NULL, 'Local dive masters sharing marine life stories sounds educational! 📚🐠', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(245, 17, 18, NULL, 'Returning divers year after year speaks to quality! 🔄✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(246, 17, 19, NULL, 'Best months for diving conditions? Planning my underwater adventure! 📅', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(247, 17, 20, 246, 'Dry season May-October is ideal, but honestly every dive here is spectacular! 🌊', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(248, 17, 21, NULL, 'This description is making me want to get certified immediately! 🤿📚', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(249, 17, 22, NULL, 'Lombok as diving pilgrimage destination is perfect description! 🕌🤿', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(250, 17, 23, NULL, 'Your underwater photography skills leveling up during trip is inspiring! 📸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(251, 17, 24, NULL, 'Marine conservation passion being infectious is beautiful! 💚🌊', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(252, 17, 25, NULL, 'World-class destination with fewer crowds is the dream! 🏝️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(253, 17, 26, NULL, 'This article convinced me Lombok > Maldives for diving! 🥇', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(254, 17, 27, NULL, 'Diverse marine life and healthy reefs make this special! 🐠🪸', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(255, 17, 28, NULL, 'Your enthusiasm for Lombok diving is absolutely contagious! 🤿❤️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- Story 18: Surabaya Industrial Heritage (8 comments)
(256, 18, 1, NULL, 'Industrial heritage transformation is such smart urban development! 🏭🎨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(257, 18, 2, NULL, 'Factory-turned-museum preserving worker stories is beautiful! 🏭📚', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(258, 18, 3, NULL, 'Former workers involved in heritage preservation is perfect! 👥💼', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(259, 18, 4, NULL, 'Building on existing community assets vs erasing them is brilliant! 🏘️', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(260, 18, 5, NULL, 'Intergenerational connection to place through heritage work is precious! 👵👶', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(261, 18, 6, NULL, 'Industrial spaces becoming creative hubs honors tradition perfectly! 🎨🏭', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(262, 18, 7, NULL, 'This model for post-industrial cities should be studied globally! 🌍', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(263, 18, 8, NULL, 'Honoring working-class history while building futures is everything! 💪✨', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Reset sequence to match the highest ID  
SELECT setval('story_comments_id_seq', (SELECT MAX(id) FROM story_comments));
